stages:
  - deploy

deploy_ftp:
  stage: deploy
  image: alpine:latest
  #rules:
    # Le pipeline ne s'exécutera que sur la branche main
  #  - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    # Installation du client FTP lftp
    - apk update
    - apk add lftp
  script:
    - echo "Démarrage du déploiement vers InfinityFree..."    
    # Commande de synchronisation FTP
    - lftp -c "set ftp:ssl-allow no; set ftp:passive-mode true; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rnv ./ /$FTP_HOME --ignore-time --parallel=1 --no-perms --exclude-glob .git* --exclude .* exclude *.md --exclude public/  --exclude .gitlab-ci.yml --exclude .git/ --exclude vendor/ --exclude docker/ --exclude docs/ --exclude scripts/ --exclude tests/ --exclude logs/ --exclude database/ --exclude config/"
    - echo "Démarrage du déploiement Dossier Public vers InfinityFree..."    
    - lftp -c "set ftp:ssl-allow no; set ftp:passive-mode true; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rnv ./public /$FTP_HOME --ignore-time --parallel=1 --no-perms"
    - echo "Déploiement terminé avec succès !"
  environment:
    name: production
