# Déclaration des étapes
stages:
  - deploy
  - backup

# =========================================================
# JOB 1 : DÉPLOIEMENT VERS LE FTP (Automatique)
# =========================================================
deploy_ftp:
  stage: deploy
  image: alpine:latest
  rules:
    # Se lance automatiquement à chaque push sur main
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk update
    - apk add lftp
  script:
    - echo "Démarrage du déploiement vers InfinityFree..."    
    - lftp -c "set ftp:ssl-allow no; set ftp:passive-mode true; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rnv ./ /$FTP_HOME --ignore-time --parallel=1 --no-perms --exclude-glob '.*' --exclude-glob '*.md' --exclude-glob 'public/' --exclude-glob 'vendor/' --exclude-glob 'docker/' --exclude-glob 'docs/' --exclude-glob 'scripts/' --exclude-glob 'tests/' --exclude-glob 'logs/' --exclude-glob 'database/' --exclude-glob 'config/'"
    - echo "Démarrage du déploiement Dossier Public..."    
    - lftp -c "set ftp:ssl-allow no; set ftp:passive-mode true; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rnv ./public /$FTP_HOME --ignore-time --parallel=1 --no-perms"
    - echo "Déploiement terminé !"
  environment:
    name: production

# =========================================================
# JOB 2 : SAUVEGARDE DEPUIS LE FTP (Manuel / Planifié)
# =========================================================
pull_from_ftp:
  stage: backup
  image: alpine:latest
  rules:
    # Uniquement via le bouton "Run pipeline" ou une tâche cron GitLab
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  before_script:
    - apk update
    - apk add lftp zip
  script:
    # Génération de l'horodatage au format ANNEE-MOIS-JOUR_HEUREhMINUTE (ex: 2026-06-13_18h50)
    - DATE_STR=$(date +%Y-%m-%d_%Hh%M)
    - 'echo "Horodatage généré : $DATE_STR"'
    - echo "Démarrage du téléchargement depuis InfinityFree..."
    - mkdir -p ./sauvegarde_locale
    - lftp -c "set ftp:ssl-allow no; set ftp:passive-mode true; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -v /htdocs ./sauvegarde_locale --parallel=2"
    
    - echo "Compression des fichiers..."
    # On utilise la variable d'horodatage dans le nom du fichier zip
    - zip -r "backup_$DATE_STR.zip" ./sauvegarde_locale/
    - echo "Sauvegarde terminée !"
  artifacts:
    name: "Sauvegarde-InfinityFree-$CI_COMMIT_SHORT_SHA"
    paths:
      - backup_*.zip
    expire_in: 1 week