# Generated by Django 5.2.13 on 2026-04-19 13:45

import adhesions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seasons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adhesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie_adhesion",
                    models.CharField(
                        choices=[
                            ("SANS_COMPETITION", "Sans compétition"),
                            ("COMPETITION_VOLLEY", "Compétition Volley"),
                            ("COMPETLIB", "Compétition Loisir"),
                            ("COMPETITION_DEP", "Compétition DEP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDE", "Validé"),
                            ("REMBOURSE", "Remboursé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                (
                    "preferences",
                    models.JSONField(
                        blank=True, default=adhesions.models.default_preferences
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "saison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adhesions",
                        to="seasons.saison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adhésion",
                "verbose_name_plural": "Adhésions",
            },
        ),
    ]
