# Generated by Django 5.2.13 on 2026-04-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesions", "0002_initial"),
        ("seasons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "genre_requis",
                    models.CharField(
                        choices=[
                            ("TOUS", "Tous"),
                            ("MASCULIN", "Masculin uniquement"),
                            ("FEMININ", "Féminin uniquement"),
                        ],
                        default="TOUS",
                        help_text="Restriction éventuelle sur le genre du joueur",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Coupe",
                "verbose_name_plural": "Coupes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="TarifAdhesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("SANS_COMPETITION", "Sans compétition"),
                            ("COMPETITION_VOLLEY", "Compétition Volley"),
                            ("COMPETLIB", "Compétition Loisir"),
                            ("COMPETITION_DEP", "Compétition DEP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "saison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="seasons.saison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif d'adhésion",
                "verbose_name_plural": "Tarifs d'adhésion",
                "ordering": ["saison__label", "categorie"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("saison", "categorie"),
                        name="unique_tarif_per_saison_categorie",
                    )
                ],
            },
        ),
    ]
