# Generated by Django 5.2.13 on 2026-04-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesions", "0004_seed_default_coupes"),
        ("members", "0002_membrefamille"),
        ("seasons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="adhesion",
            name="unique_adhesion_per_season",
        ),
        migrations.AddField(
            model_name="adhesion",
            name="membre_famille",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adhesions",
                to="members.membrefamille",
                verbose_name="Membre de la famille (si pas le responsable)",
            ),
        ),
        migrations.AlterField(
            model_name="adhesion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adhesions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable / payeur",
            ),
        ),
        migrations.AddIndex(
            model_name="adhesion",
            index=models.Index(
                fields=["membre_famille"], name="adhesions_a_membre__2ec25c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="adhesion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("membre_famille__isnull", True)),
                fields=("user", "saison"),
                name="unique_adhesion_user_per_season",
            ),
        ),
        migrations.AddConstraint(
            model_name="adhesion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("membre_famille__isnull", False)),
                fields=("membre_famille", "saison"),
                name="unique_adhesion_membre_per_season",
            ),
        ),
    ]
