# Generated by Django 5.2.13 on 2026-04-20 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesions", "0005_remove_adhesion_unique_adhesion_per_season_and_more"),
        ("members", "0002_membrefamille"),
        ("seasons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adhesion",
            name="helloasso_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="adhesion",
            name="helloasso_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="adhesion",
            name="helloasso_payer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="adhesion",
            name="helloasso_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="adhesion",
            name="helloasso_webhook_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="adhesion",
            name="last_webhook_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="adhesion",
            index=models.Index(
                fields=["helloasso_webhook_id"], name="adhesions_a_helloas_2ee277_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adhesion",
            index=models.Index(
                fields=["helloasso_payment_id"], name="adhesions_a_helloas_82f4fd_idx"
            ),
        ),
    ]
