# Generated by Django 5.2.13 on 2026-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesions", "0006_adhesion_helloasso_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adhesion",
            name="helloasso_checkout_intent_id",
            field=models.CharField(
                blank=True,
                help_text="ID du checkout intent (créé à l'initialisation du paiement)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adhesion",
            name="helloasso_payment_receipt_url",
            field=models.URLField(
                blank=True,
                help_text="URL de l'attestation de paiement HelloAsso",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adhesion",
            name="helloasso_order_id",
            field=models.CharField(
                blank=True,
                help_text="ID de la commande HelloAsso",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adhesion",
            name="helloasso_payment_id",
            field=models.CharField(
                blank=True,
                help_text="ID unique du paiement (reçu via webhook)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
