# Generated by Django 5.2.13 on 2026-04-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembreFamille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="nom")),
                ("date_of_birth", models.DateField(verbose_name="date de naissance")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MASCULIN", "Masculin"),
                            ("FEMININ", "Féminin"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                        verbose_name="genre",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="famille",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable (adhérent principal)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre de la famille",
                "verbose_name_plural": "Membres de la famille",
                "ordering": ["last_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "responsable",
                            "first_name",
                            "last_name",
                            "date_of_birth",
                        ),
                        name="unique_membre_famille",
                    )
                ],
            },
        ),
    ]
