# Generated by Django 5.2.13 on 2026-04-19 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adhesions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adhesion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adhesions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adhesion",
            index=models.Index(fields=["user"], name="adhesions_a_user_id_7c1f3f_idx"),
        ),
        migrations.AddIndex(
            model_name="adhesion",
            index=models.Index(
                fields=["saison"], name="adhesions_a_saison__6c7fe6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="adhesion",
            constraint=models.UniqueConstraint(
                fields=("user", "saison"), name="unique_adhesion_per_season"
            ),
        ),
    ]
