# Generated by Django 5.2.13 on 2026-04-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="equipe_groupe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="teams.equipegroupe",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["date_evenement"], name="content_eve_date_ev_e183a9_idx"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="content.event",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="content_pos_slug_a791ce_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["categorie"], name="content_pos_categor_890847_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["date_publication"], name="content_pos_date_pu_4dc16c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["equipe_groupe"], name="content_doc_equipe__e47c0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["permission"], name="content_doc_permiss_9d23c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["event"], name="content_pho_event_i_5fb5ba_idx"),
        ),
    ]
