# Generated by Django 5.2.13 on 2026-04-19 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seasons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipeGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="ex: M18F, DEP, CompetLib", max_length=50
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("SANS_COMPETITION", "Sans compétition"),
                            ("COMPETITION_VOLLEY", "Compétition Volley"),
                            ("COMPETLIB", "Compétition Loisir"),
                            ("COMPETITION_DEP", "Compétition DEP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "joueurs",
                    models.ManyToManyField(
                        blank=True, related_name="equipes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "saison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipes",
                        to="seasons.saison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipe / Groupe",
                "verbose_name_plural": "Équipes / Groupes",
                "ordering": ["saison__label", "nom"],
                "indexes": [
                    models.Index(
                        fields=["saison"], name="teams_equip_saison__10ad9f_idx"
                    ),
                    models.Index(fields=["slug"], name="teams_equip_slug_d9a332_idx"),
                ],
            },
        ),
    ]
