# Generated by Django 5.2.13 on 2026-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("fichier", models.FileField(upload_to="documents/%Y/%m/")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FACTURE", "Facture"),
                            ("CERTIFICAT", "Certificat médical"),
                            ("REGLEMENTAIRE", "Document réglementaire"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("GROUPE_RESTREINT", "Équipe/Groupe restreint"),
                            ("ADHERENTS_ONLY", "Adhérents seulement"),
                            ("BUREAU_ONLY", "Bureau seulement"),
                        ],
                        default="BUREAU_ONLY",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_evenement", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["-date_evenement"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/%Y/%m/")),
                ("alt", models.CharField(blank=True, max_length=200)),
                (
                    "tags_equipes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de slugs d'équipes (ex: ['m18f','dep'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("contenu", models.TextField(help_text="HTML CKEditor")),
                ("categorie", models.CharField(max_length=50)),
                ("date_publication", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article de blog",
                "verbose_name_plural": "Articles de blog",
                "ordering": ["-date_publication"],
            },
        ),
    ]
