# Generated by Django 5.2.13 on 2026-04-20 13:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categorie",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="contenu",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Contenu"),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80, verbose_name="label")),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("PAGE", "Page statique"),
                            ("ROUTE", "Route nommée"),
                            ("URL", "URL brute"),
                            ("NONE", "Aucun (parent seulement)"),
                        ],
                        default="NONE",
                        max_length=10,
                        verbose_name="type de lien",
                    ),
                ),
                (
                    "link_value",
                    models.CharField(
                        blank=True,
                        help_text="PAGE : slug de la page statique • ROUTE : nom de route Django (ex: blog_list) • URL : URL brute (ex: /adhesion/) • NONE : laisser vide",
                        max_length=255,
                        verbose_name="valeur du lien",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Attention : la suppression d'un parent supprime ses enfants.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="content.menuitem",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée de menu",
                "verbose_name_plural": "Menu — entrées",
                "ordering": ["parent__ordre", "parent_id", "ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageStatique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "contenu",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Contenu"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="publiée"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page statique",
                "verbose_name_plural": "Pages statiques",
                "ordering": ["titre"],
                "indexes": [
                    models.Index(fields=["slug"], name="content_pag_slug_0ba074_idx"),
                    models.Index(
                        fields=["is_published"], name="content_pag_is_publ_5251e4_idx"
                    ),
                ],
            },
        ),
    ]
